name: Import Data to Auth0

on:
  workflow_dispatch:

jobs:
  job1:
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Auth0-Import.yml@main
    with:
      branch_name: 'main'
      target_folder: 'target'
    secrets:
      auth0_secrets: ${{ secrets.AUTH0_CREDENTIALS }}
      gcp_service_account: ${{ secrets.NABARUN_FIREBASE_SERVICE_ACCOUNT_STAGE }}
